### ISSUE TITLE
There are no two parameters in DQN():checkpoint_freq and checkpoint_path

### ISSUE THREAD

**Issue by yahaha6** [doctorsrn/gym_vrep#1]
Traceback (most recent call last):
  File "D:/Personal/My_Subject/Simulation/MySubject_simulation/gym_vrep-master/gym_vrep/envs/train_vrep.py", line 101, in <module>
    main(args)
  File "D:/Personal/My_Subject/Simulation/MySubject_simulation/gym_vrep-master/gym_vrep/envs/train_vrep.py", line 86, in main
    tensorboard_log='./log',
TypeError: __init__() got an unexpected keyword argument 'checkpoint_freq'

There are no two parameters in DQN():checkpoint_freq and checkpoint_path,but these two parameters are used in the function callback().How to solve this problem？

**Comment by doctorsrn** [comment]
@lzg0825 Hi, sorry for late reply. I think this proplem is caused by the different api between the different versions of stable-baselines. As you see there are no two  parameters in this version [stable-baselines](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/deepq/dqn.py), but this version [stable-baseliens](https://github.com/hill-a/stable-baselines/blob/HER/stable_baselines/deepq/dqn.py) has these two parameters. So, you can try the latter one. And I also upload the the version of stable-baselines to the [Google Driver](https://drive.google.com/file/d/1c95rPDlj6gpcNV42qxxAU_F-I6z4J08u/view?usp=sharing) I used before. You can install it locally.

> Traceback (most recent call last):
> File "D:/Personal/My_Subject/Simulation/MySubject_simulation/gym_vrep-master/gym_vrep/envs/train_vrep.py", line 101, in
> main(args)
> File "D:/Personal/My_Subject/Simulation/MySubject_simulation/gym_vrep-master/gym_vrep/envs/train_vrep.py", line 86, in main
> tensorboard_log='./log',
> TypeError: **init**() got an unexpected keyword argument 'checkpoint_freq'
> 
> There are no two parameters in DQN():checkpoint_freq and checkpoint_path,but these two parameters are used in the function callback().How to solve this problem？
